permalink: pretty

collections:
  data:
    about:
    contact:
    services:
      output: true
  work:
    output: true
    permalink: /:collection/:year/:month/:slug/
  play:
    output: true
    permalink: /:collection/:year/:month/:slug/
