permalink: pretty

collections:
  pages:
    about:
    contact:
    services:
      allservices:
  work:
    output: true
    permalink: /:collection/:year/:month/:slug/
  play:
    output: true
    permalink: /:collection/:year/:month/:slug/
