backend:
  name: github
  repo: kent-photgraphy/kent-photography-website

media_folder: "images/uploads"

collections:
  - label: "pages"
    name: "pages"
    files:
      - label: "About page"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "Text"
            name: "text"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
