backend:
  name: github
  repo: kent-photgraphy/kent-photography-website

media_folder: "/images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About page"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "Text"
            name: "text"
            widget: "text"
          - label: "Image"
            name: "image"
            widget: "image"
      - label: "Contact page"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - label: "Social media"
            name: "socialmedia"
            widget: "list"
            fields:
              - label: "Social media name"
                name: "socialmedialink"
                widget: "string"
              - label: "Social media link"
                name: "socialmedialinkUrl"
                widget: "string"
      - label: "Services page"
        name: "service"
        file: "_data/services.yml"
        fields:
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - label: "Services"
                name: "services"
                widget: "string"
              - label: "Services link"
                name: "serviceslink"
                widget: "string"
              - label: "Services link"
                name: "servicesimage"
                widget: "image"
  - label: "Work"
    name: "work"
    folder: "_work"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "posts"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "desc"
        widget: "string"
      - label: "Thumbnail image"
        name: "thumb"
        widget: "image"
      - label: "Body"
        name: "text"
        widget: "markdown"
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Caption"
            name: "figcaption"
            widget: "string"
  - label: "Play"
    name: "play"
    folder: "_play"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "posts"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "desc"
        widget: "string"
      - label: "Thumbnail image"
        name: "thumb"
        widget: "image"
      - label: "Body"
        name: "text"
        widget: "markdown"
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Caption"
            name: "figcaption"
            widget: "string"
