backend:
  name: github
  repo: kent-photgraphy/kent-photography-website

media_folder: "images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About page"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "Text"
            name: "text"
            widget: "text"
          - label: "Image"
            name: "image"
            widget: "image"
      - label: "Contact page"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - label: "Social media Link"
            name: "socialmedialink"
            widget: "list"
            fields:
              - label: "Social media Link"
                name: "socialmedialink"
                widget: "string"
              - label: "Social media Link URL"
                name: "socialmedialinkUrl"
                widget: "string"
